# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'AGLNetManagerDemo_Pod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  
  use_frameworks!

  # Pods for AGLNetManagerDemo_Pod

  pod 'AGLNetManager', :git => 'https://github.com/AngryLi/NetManager.git', :tag => '0.0.3'

end
